solution:
  name: "Cavity10G"
  type: "Eigenmode" # "Eigenmode" or "Modal"
  options:
    # Common options
    max_passes     : 20
    max_delta_s    : 0.02
    SaveFields     : True
    # Eigen mode
    min_frequency: "2GHz"
    n_mode       : 3
    copy_mesh    : True
    # Driven modal mode
    adaptive_solution_type  : "single" # single, broadband
    start_frequency         : 7.0
    stop_frequency          : 13.0
    medium_frequency        : "eval:0.5*(start_frequency + stop_frequency)"
    adaptive_setup_frequency: "eval:medium_frequency"
    num_of_freq_points      : 601
    n_waveport_mode         : 1


parameter:
  "$cavity_width"     : "17mm" #x
  "$cavity_length"    : "6mm"  #y
  "$cavity_height"    : "16mm" #z
  "cavity_fillet"     : "2.5mm" # Not configurable 
  "$port_distance"    : "10mm"
  "$port_height"      : "7mm"
  "$port_in_depth"    : "3mm"
  "$port_out_depth"   : "5.5mm"
  "$port_inner_radius": "0.3mm"
  "$port_outer_radius": "2.1mm"
  "$chip_inductance"  : "4.5nH"
  "$chip_gap"         : "300um"  
  "$chip_width"       : "400um" 
  "$chip_height"      : "200um" 
  "$chip_theta"       : "0deg"  # 0deg
  "$chip_pos_z_ratio" : "0.5"
  "$chip_pos_z"       : "$chip_pos_z_ratio*$cavity_height"
  "$chip_pos_y"       : "0"
  "$chip_pos_x"       : "0"
  "$wafer_thickness"  : "0.525mm"
  "$wafer_width"      : "2mm"
  "$wafer_height"     : "$cavity_length"

## Under construction...
# devices:
#   - type: box
#     config:
#       origin: ["-$box_length/2", "-$box_length/2", "$outer_height - $box_height"]
#       sizes: ["$box_length", "$box_length", "$box_height"]
#       name: "box"
#       material: "copper"
#   - type: clone
#     config:
#       name: 


sweep:
  list:
    Eigenmode:
      - "$chip_inductance"
    Modal: []
      # - "$chip_theta"
      # - "$chip_pos_z_ratio" 
  config:
    "$chip_inductance":
        - start_point   : 1.5
          end_point     : 3.5
          step          : 0.2
          units         : "nH"
          variation_type: "LinearStep"
        - start_point   : 4
          end_point     : 6
          step          : 0.5
          units         : "nH"
          variation_type: "LinearStep"
    "$chip_theta": 
        - start_point   : 0
          end_point     : 0
          step          : 1
          units         : "deg"
          variation_type: "LinearCount"
        # - start_point   : -90
        #   end_point     : 45
        #   step          : 4
        #   units         : "deg"
        #   variation_type: "LinearCount"
    "$chip_gap": 
        - start_point   : 20
          end_point     : 520
          step          : 100
          units         : "um"
          variation_type: "LinearStep"
        - start_point   : 1020
          end_point     : 2020
          step          : 500
          units         : "um"
          variation_type: "LinearStep"
    "$chip_width": 
        - start_point   : 100
          end_point     : 1000
          step          : 150
          units         : "um"
          variation_type: "LinearStep"
        - start_point   : 1500
          end_point     : 3000
          step          : 500
          units         : "um"
          variation_type: "LinearStep"
    "$chip_pos_z_ratio": 
        - start_point   : 0.4
          end_point     : 0.8
          step          : 0.1
          units         : null
          variation_type: "LinearStep"
    "$chip_height": 
        - start_point   : 500
          end_point     : 3000
          step          : 500
          units         : "um"
          variation_type: "LinearStep"